# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [227]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [228]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda\\Library\\include']
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [229]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [230]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b.size)
print(b.itemsize)

9
4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [231]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [232]:
w=np.zeros(10)
w[4]=1
print(w)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [233]:
s=np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [234]:
d=s[::-1]
print(d)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [235]:
e=np.arange(9)
d=e.reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [236]:
y=np.array([1,2,0,0,4,0])
print(np.nonzero(y))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [237]:
g=np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [238]:
f=np.random.rand(3,3,3)
print(f)

[[[0.81353786 0.63967684 0.58215456]
  [0.33866082 0.15795072 0.04498048]
  [0.22904266 0.83110429 0.99498661]]

 [[0.69721556 0.16694956 0.53518508]
  [0.38701308 0.44405295 0.22909738]
  [0.18696215 0.45098047 0.99659738]]

 [[0.85664145 0.25433795 0.60419975]
  [0.66059368 0.13925109 0.55756851]
  [0.99325934 0.05132172 0.52894353]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [239]:
u=np.random.rand(10,10)
#print(u)
print(u.min())
print(u.max())

0.008128523184806724
0.9728079946516086


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [240]:
p=np.random.rand(30)
#print(p)
print(p.mean())

0.6124513357066587


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [241]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [242]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [243]:
a=0 * np.nan
b=np.nan == np.nan
e=np.inf > np.nan
t=np.nan - np.nan
u=0.3 == 3 * 0.1
print(a,b,e,t,u)

nan False False nan False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [244]:
u = np.diag(1+np.arange(4),k=-1)
print(u)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [245]:
o=np.zeros((8,8),dtype=int)
o[1::2,::2]=1
o[::2,1::2]=1
print(o)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [246]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [247]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [248]:
t = np.random.rand(5,5)
i=t.max()
j=t.min()
Z = ((t - i)/(i - j))
print(Z)


[[-0.33617695 -0.05419024 -0.97168079 -0.31681551 -0.19521401]
 [-0.39164132 -0.37546907 -0.74065867 -0.22130074 -0.30724246]
 [-0.97613313 -0.34626662 -0.75075576 -0.81805413  0.        ]
 [-0.11408539 -0.45467333 -0.65236893 -1.         -0.91727768]
 [-0.53824058 -0.80653226 -0.96398694 -0.86387765 -0.93051718]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [249]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [250]:
p = np.dot(np.ones((5,3)), np.ones((3,2)))
print(p)
h = np.ones((5,3)) @ np.ones((3,2))
print(h)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [251]:
g = np.arange(11)
g[(3 < g) & (g <= 8)] *= -1
print(g)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [252]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [253]:
Z**Z
Z <- Z
1j*Z

<ipython-input-253-c0757055e392>:1: RuntimeWarning: invalid value encountered in power
  Z**Z


array([[-0.-0.33617695j, -0.-0.05419024j, -0.-0.97168079j,
        -0.-0.31681551j, -0.-0.19521401j],
       [-0.-0.39164132j, -0.-0.37546907j, -0.-0.74065867j,
        -0.-0.22130074j, -0.-0.30724246j],
       [-0.-0.97613313j, -0.-0.34626662j, -0.-0.75075576j,
        -0.-0.81805413j,  0.+0.j        ],
       [-0.-0.11408539j, -0.-0.45467333j, -0.-0.65236893j,
        -0.-1.j        , -0.-0.91727768j],
       [-0.-0.53824058j, -0.-0.80653226j, -0.-0.96398694j,
        -0.-0.86387765j, -0.-0.93051718j]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [254]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-254-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-254-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [255]:
k = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(k)), k))
print(np.where(k>0, np.ceil(k), np.floor(k)))

[ 5.  5.  2.  4.  2. -8.  7. -5.  1. -5.]
[ 5.  5.  2.  4.  2. -8.  7. -5.  1. -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [256]:
j = np.random.randint(0,10,10)
k = np.random.randint(0,10,10)
print(np.intersect1d(j,k))

[0 1 2 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [257]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [258]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-258-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [259]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2021-09-30 2021-10-01 2021-10-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [260]:
date = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [261]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [262]:
j = np.random.uniform(0,10,10)
print (j - j%1)
print (np.floor(j))
print (np.ceil(j-1))
print (j.astype(int))
print (np.trunc(j))


[0. 6. 3. 9. 4. 2. 3. 6. 1. 1.]
[0. 6. 3. 9. 4. 2. 3. 6. 1. 1.]
[-0.  6.  3.  9.  4.  2.  3.  6.  1.  1.]
[0 6 3 9 4 2 3 6 1 1]
[0. 6. 3. 9. 4. 2. 3. 6. 1. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [263]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [264]:
def gen():
    for x in range(10):
        yield x
f = np.fromiter(gen(),dtype=float,count=-1)
print(f)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [265]:
i= np.linspace(0,1,12,endpoint=True)[1:-1]
print(i)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [266]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.15226429 0.15958029 0.19725151 0.5117855  0.65287832 0.87451338
 0.91573117 0.95610815 0.95635524 0.95670845]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [267]:
s = np.arange(10)
np.add.reduce(s)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [268]:
a = np.random.randint(0,2,5)
l = np.random.randint(0,2,5)
eq = np.allclose(a,l)
print(eq)


False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [269]:
p= np.zeros(10)
p.flags.writeable = False
p[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [270]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.44991593 0.10484798 0.77767673 0.85836505 1.01168377 1.14425224
 1.00999925 0.97512626 0.80674331 0.56346514]
[0.47503896 0.16031796 0.77839492 0.60597415 0.91651964 0.93503088
 0.99902476 0.24776897 1.2134606  1.38204201]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [271]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.01604282 0.63820028 0.         0.10421626 0.38498657 0.00109023
 0.63143201 0.17812403 0.86896404 0.0581976 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [272]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [273]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [274]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [275]:

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [276]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

96


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [277]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
('y', float, 1)]),
('color', [ ('r', float, 1),
('g', float, 1),
('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-277-6442ab7994a7>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [278]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


[[0.         0.5405439  0.14326033 0.47588307 0.51493358 0.68663859
  0.32960684 0.17730697 0.33085382 0.43096327]
 [0.5405439  0.         0.47511482 0.06717769 0.91831211 1.17572837
  0.44214811 0.53589253 0.77435991 0.21148201]
 [0.14326033 0.47511482 0.         0.40793813 0.65801282 0.8209956
  0.18638671 0.2963186  0.47410942 0.32274915]
 [0.47588307 0.06717769 0.40793813 0.         0.87080742 1.12036787
  0.38110891 0.48144313 0.72078611 0.16013959]
 [0.51493358 0.91831211 0.65801282 0.87080742 0.         0.31402302
  0.84398031 0.40076747 0.18510423 0.8961261 ]
 [0.68663859 1.17572837 0.8209956  1.12036787 0.31402302 0.
  1.00096398 0.63983826 0.40277123 1.11185232]
 [0.32960684 0.44214811 0.18638671 0.38110891 0.84398031 1.00096398
  0.         0.47016672 0.66039802 0.23808754]
 [0.17730697 0.53589253 0.2963186  0.48144313 0.40076747 0.63983826
  0.47016672 0.         0.23941202 0.49536126]
 [0.33085382 0.77435991 0.47410942 0.72078611 0.18510423 0.40277123
  0.66039802 0.239412

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [279]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [280]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [281]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [282]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [283]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [284]:
x = np.random.rand(5, 10)
l = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(y)

[[-0.032899    0.16956062  0.02531915  0.04136634 -0.44863084  0.0715407
   0.45289315 -0.44417962 -0.04559971  0.21062923]
 [-0.01919258  0.01228337 -0.06218543  0.25115169 -0.30351832 -0.01464584
  -0.11676432  0.6089172  -0.27451269 -0.08153308]
 [ 0.09949224 -0.46630408  0.11843262 -0.08728107 -0.22147188  0.09858241
   0.0080249   0.0262238   0.21458684  0.20971423]
 [ 0.36992598 -0.23691581 -0.4142343   0.03717697 -0.19309238  0.27361764
  -0.27175337  0.25889094  0.06914222  0.1072421 ]
 [-0.11142752 -0.33648581  0.06145831 -0.21126844 -0.115088    0.24879582
   0.06678318 -0.10445814  0.0101579   0.4915327 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [285]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 8 0]
 [1 2 7]
 [5 6 7]]
[[1 2 7]
 [5 6 7]
 [5 8 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [286]:
p = np.random.randint(0,3,(3,10))
print((~p.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [287]:
p = np.random.uniform(0,1,10)
z = 0.5
m = p.flat[np.abs(p - z).argmin()]
print(m)


0.48561271633097614


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [288]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [289]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [290]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 4. 4. 3. 1. 1. 3. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [291]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [292]:
w,h = 16,16
l= np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
h = l[...,0]*256*256 + l[...,1]*256 +l[...,2]
n = len(np.unique(h))
print(np.unique(l))


[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [293]:
A = np.random.randint(0,10,(3,4,3,4))
i= A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(i)

[[60 68 41 61]
 [47 59 42 59]
 [53 53 60 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [294]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.35486004 0.28119796 0.4595169  0.58048771 0.31106104 0.53463537
 0.46521735 0.47334442 0.59040812 0.40541849]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [295]:
o= np.random.uniform(0,1,(5,5))
p= np.random.uniform(0,1,(5,5))
np.diag(np.dot(o, p))
np.sum(o * p.T, axis=1)
np.einsum("ij,ji->i", o, p)

array([0.98153974, 1.29559471, 1.15857021, 1.10075831, 1.21002844])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [296]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [297]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [298]:

sw = np.arange(25).reshape(5,5)
sw[[0,1]] = sw[[1,0]]
print(sw)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [299]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 72) ( 1, 81) ( 3, 34) ( 3, 57) ( 3, 58) ( 3, 75) (15, 60) (15, 86)
 (25, 48) (25, 50) (34, 57) (39, 69) (39, 83) (40, 72) (40, 78) (48, 50)
 (50, 79) (50, 84) (52, 69) (52, 93) (58, 75) (60, 86) (69, 71) (69, 83)
 (69, 89) (69, 93) (71, 89) (72, 78) (72, 81) (79, 84)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [300]:
j = np.bincount([1,1,2,3,4,4,6])
k = np.repeat(np.arange(len(j)), j)
print(k)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [301]:
def avg(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
v = np.arange(20)
print(avg(v, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [302]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [303]:
f= np.random.randint(0,2,100)
np.logical_not(f, out=f)

q = np.random.uniform(-1.0,1.0,100)
np.negative(q, out=q)



array([ 0.02750427, -0.49175979, -0.62936981,  0.79185754,  0.48497928,
        0.42536955,  0.49964412,  0.04484123, -0.75353083,  0.72303293,
       -0.66934592,  0.06013071,  0.07362915,  0.89654063, -0.22480697,
        0.51252086,  0.79687477,  0.81379014, -0.32147996, -0.60875402,
        0.21216234,  0.33633391, -0.9140818 ,  0.61178359, -0.03520931,
        0.5130867 ,  0.5247337 ,  0.51383096, -0.06164147, -0.7691444 ,
       -0.10776047,  0.240465  ,  0.46119585,  0.73571338, -0.55720571,
       -0.93267991, -0.51658397,  0.34323598, -0.00589321, -0.92028935,
       -0.81999748, -0.51547471, -0.41168907,  0.03805488, -0.04894327,
        0.78630042, -0.74433518, -0.77478418, -0.79156905,  0.93074812,
       -0.03013802, -0.3721333 ,  0.30371209,  0.59749635,  0.89833395,
       -0.76983754,  0.48587399,  0.07548102, -0.71133666,  0.70337738,
       -0.91625873,  0.20909986, -0.62068641, -0.87528472,  0.81959214,
       -0.42687154, -0.16365706,  0.41005155, -0.03042247,  0.06

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [304]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.44881557  6.20147535  1.61015516  0.52532653  0.03851939  5.32857987
 10.84860352 12.38563683  0.36918056  2.02208888]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [305]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.36286145 13.8277589   0.72903017  7.44352449  0.63794979  6.82233376
   4.06815062  7.76598313  1.38758545  2.72485093]
 [ 0.74305777  6.46990113  4.6613868  10.58546874  6.81371323  3.07294265
  13.66348111  5.68229386  9.44009272  4.25775573]
 [ 0.90436686  8.66654481  2.7469939  10.72846206  6.1470889   0.95243783
  11.34536412  6.99442728  7.16768289  2.10842445]
 [10.96619872  4.92923549  9.66879689  2.49855923  6.85684019  5.45286627
   8.72529473  3.52620781  9.45306536  6.54253764]
 [ 9.0077305  13.51711074  0.20822986  6.53733385  0.2325156   7.20571314
   3.94806771  7.01486121  1.60107742  2.36785321]
 [17.13313084 13.13364982  2.52252494  1.97844893  9.3618752  13.38367467
   0.06011944  1.36566523  0.96396568  1.48432982]
 [ 7.46316112 19.02188764  6.62172901 12.62116608  4.33146616  8.10418047
   1.03345558 13.95794525  3.39646247  8.09683465]
 [10.39705017 10.99334072  2.92620624  3.06060038  3.07356809  7.32398251
   4.93676301  3.39281404  3.80859035  0.29986543]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [306]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 0 8 6 3 4 8 8 7 9]
 [6 6 2 3 1 3 2 3 6 3]
 [3 7 8 0 9 4 1 5 3 3]
 [9 0 4 4 6 5 0 0 2 4]
 [3 8 4 7 9 9 9 5 8 8]
 [3 0 4 7 8 6 7 0 4 2]
 [2 6 8 3 6 9 8 4 4 3]
 [9 8 3 4 6 4 5 7 4 0]
 [1 6 1 4 0 4 4 9 1 3]
 [1 8 1 9 8 2 0 8 7 0]]
[[0 0 0 0 0]
 [0 7 0 8 6]
 [0 6 6 2 3]
 [0 3 7 8 0]
 [0 9 0 4 4]]


<ipython-input-306-0a369be77cd4>:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [307]:
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [308]:
Z = np.random.uniform(0,1,(10,10))
u,s,v = np.linalg.svd(Z) 
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [309]:
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [310]:
t = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (t.shape[0]-3)
j = 1 + (t.shape[1]-3)
p = stride_tricks.as_strided(t, shape=(i, j, n, n), strides=t.strides + t.strides)
print(p)


[[[[3 2 4]
   [4 4 1]
   [3 3 0]]

  [[2 4 1]
   [4 1 0]
   [3 0 0]]

  [[4 1 3]
   [1 0 2]
   [0 0 0]]

  [[1 3 3]
   [0 2 1]
   [0 0 0]]

  [[3 3 2]
   [2 1 4]
   [0 0 4]]

  [[3 2 3]
   [1 4 1]
   [0 4 1]]

  [[2 3 2]
   [4 1 0]
   [4 1 2]]

  [[3 2 3]
   [1 0 2]
   [1 2 3]]]


 [[[4 4 1]
   [3 3 0]
   [1 1 0]]

  [[4 1 0]
   [3 0 0]
   [1 0 4]]

  [[1 0 2]
   [0 0 0]
   [0 4 1]]

  [[0 2 1]
   [0 0 0]
   [4 1 0]]

  [[2 1 4]
   [0 0 4]
   [1 0 3]]

  [[1 4 1]
   [0 4 1]
   [0 3 4]]

  [[4 1 0]
   [4 1 2]
   [3 4 1]]

  [[1 0 2]
   [1 2 3]
   [4 1 3]]]


 [[[3 3 0]
   [1 1 0]
   [0 2 2]]

  [[3 0 0]
   [1 0 4]
   [2 2 1]]

  [[0 0 0]
   [0 4 1]
   [2 1 4]]

  [[0 0 0]
   [4 1 0]
   [1 4 4]]

  [[0 0 4]
   [1 0 3]
   [4 4 2]]

  [[0 4 1]
   [0 3 4]
   [4 2 2]]

  [[4 1 2]
   [3 4 1]
   [2 2 2]]

  [[1 2 3]
   [4 1 3]
   [2 2 3]]]


 [[[1 1 0]
   [0 2 2]
   [1 2 1]]

  [[1 0 4]
   [2 2 1]
   [2 1 4]]

  [[0 4 1]
   [2 1 4]
   [1 4 3]]

  [[4 1 0]
   [1 4 4]
   [4 3 2]]

  [[1 0 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [311]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  8 17  5  3]
 [ 8  1  9  8 10]
 [17  9  4 42 10]
 [ 5  8 42  6  9]
 [ 3 10 10  9  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [312]:
p, n = 10, 20
g = np.ones((p,n,n))
q = np.ones((p,n,1))
d = np.tensordot(g, q, axes=[[0, 2], [0, 1]])
print(d)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [313]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [314]:
def iterate(game):
    N = (game[0:-2,0:-2] + game[0:-2,1:-1] + game[0:-2,2:] +
         game[1:-1,0:-2]                + game[1:-1,2:] +
         game[2:  ,0:-2] + game[2:  ,1:-1] + game[2:  ,2:])
    birth = (N==3) & (game[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (game[1:-1,1:-1]==1)
    game[...] = 0
    game[1:-1,1:-1][birth | survive] = 1
    return game

game = np.random.randint(0,2,(50,50))
for i in range(100): game = iterate(game)
print(game)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 1 0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1
  1 0 1 0 1 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0
  0 0 1 0 1 1 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1
  0 0 0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [315]:
l = np.arange(10000)
np.random.shuffle(l)
n = 5
print (l[np.argsort(l)[-n:]])
print (l[np.argpartition(-l,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [316]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    i = np.indices(shape, dtype=int)
    i = i.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        i[:, n] = arrays[n][i[:, n]]
        return i
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [317]:
Z = np.array([("Hello", 2.5, 3),
("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [318]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.12 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
786 ms ± 60.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
470 ms ± 54.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [319]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)


[0 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [320]:
q = np.random.randint(0,5,(10,3))
print(q)
l = np.all(q[:,1:] == q[:,:-1], axis=1)
k = q[~l]
k = q[q.max(axis=1) != q.min(axis=1),:]
print(k)



[[4 0 2]
 [3 2 1]
 [3 1 3]
 [1 0 4]
 [2 1 0]
 [3 3 3]
 [0 4 4]
 [0 4 0]
 [4 0 4]
 [0 0 0]]
[[4 0 2]
 [3 2 1]
 [3 1 3]
 [1 0 4]
 [2 1 0]
 [0 4 4]
 [0 4 0]
 [4 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [321]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [322]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [323]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

w=np.einsum('i->', A)       
o=np.einsum('i,i->i', A, B) 
h=np.einsum('i,i', A, B)    
f=np.einsum('i,j->ij', A, B)  
print(w,o,h,f)

6.128686405012968 [0.46734715 0.3055648  0.01266201 0.47797958 0.42870409 0.05372108
 0.66426581 0.56412863 0.42068854 0.02997002] 3.425031716945999 [[0.46734715 0.44049247 0.05364155 0.56104315 0.58633744 0.14917002
  0.86279398 0.5469236  0.89698927 0.0896419 ]
 [0.3241936  0.3055648  0.03721056 0.38918949 0.40673586 0.10347761
  0.59851073 0.37939491 0.62223163 0.06218361]
 [0.11031662 0.10397761 0.01266201 0.13243342 0.13840411 0.03521137
  0.20366127 0.12910053 0.21173302 0.02115984]
 [0.39815546 0.37527668 0.04569981 0.47797958 0.499529   0.1270851
  0.7350556  0.46595046 0.7641882  0.07637024]
 [0.34170363 0.32206868 0.03922034 0.41021002 0.42870409 0.10906655
  0.63083693 0.39988643 0.65583901 0.06554221]
 [0.16830724 0.15863598 0.01931811 0.20205029 0.2111596  0.05372108
  0.31072079 0.19696537 0.32303565 0.03228303]
 [0.35981096 0.33913553 0.04129868 0.43194759 0.45142169 0.11484613
  0.66426581 0.42107694 0.69059279 0.06901538]
 [0.48204887 0.45434941 0.055329   0.57869235 0

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [324]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [325]:
X = np.asarray([[5.6, 3.4, 8.9, 9.0],
                [4.0, 7.2, 0.5, 6.2],
                [9.5, 6.5, 0.0, 0.1]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [327]:
x = np.random.randn(100) 
smp = 1000 
idx = np.random.randint(0, x.size, (smp, x.size))
means = x[idx].mean(axis=1)
con = np.percentile(means, [2.5, 97.5])
print(con)

[-0.2695133   0.15062284]
